### ISSUE TITLE
Upgrade to newest version of react-apollo?

### ISSUE THREAD

**Issue by carsonxyz** [adamjking3/simpler-universal-react-redux-example#2]
Thanks so much for this awesome stack. Any plans to upgrade the starter to the newest builds of apollo server and react-apollo to take advantage of some of the recent improvements with SSR? It looks like they've really made some good changes.

**Comment by notadamking** [comment]
I am currently working on a project that is using a modified version of this stack in production. I didn't have any plans to update this but if I find the time I'll see if I can port the changes I've made to this repo.

**Comment by carsonxyz** [comment]
Awesome, thanks for the prompt reply. If there is anything I can do to help out as well, in terms of updating the code or a PR, let me know. I'd be glad to do what I can.

Since you have already made changes from this stack in a production project, I won't just go ahead and submit a PR as it may be different from your thinking or how you've build it for the other project. That said, if you don't have the time, but can give me some input on how you'd like it updated or even snippets of how the other project is architected with the new code, I can use that and submit a PR in the same style. Again, love the project and happy to do what I can.

**Comment by notadamking** [comment]
@carsonperrotti I have moved from redux to mobx in my production stack as I feel it has greatly simplified my code, but this makes it hard to port changes from my current stack to this repo. If you want to submit a PR, I would love to look over your changes and commit them if they all look good. Otherwise, would you be at all interested in the updated mobx version of this stack?

**Comment by carsonxyz** [comment]
I just had to do some research on Mobx, as I've never used it before. It sounds quite interesting. 

Are you still using it with Apollo? It seems quite interesting as it seems to add some reactivity to the data source, not unlike Tracker for Meteor. I'd be interested in checking it out if it makes state management more simple. 👍
